services:
  shutter:
    build:
      args:
        NETWORK: chiado
        CHAIN_PORT: 27656
        KEYPER_PORT: 24003
        KEYPER_METRICS_PORT: 9100
        ASSETS_VERSION: shutter-api-chiado-102000-v0.0.0
    ports:
      - "24003:24003"
      - "27656:27656"
      - "27660:27660"
      - "9200:9100"

  metrics:
    build:
      args:
        NETWORK: chiado
        ASSETS_VERSION: shutter-api-chiado-102000-v0.0.0